### ISSUE TITLE
Console warning "Failed to update session information!"

### ISSUE THREAD

**Issue by shantek** [MCXboxBroadcast/Broadcaster#101]
Everything seems to mostly function correctly with the extension however I'm getting this error spammed in to my console pretty frequently. It doesn't seem to stop the players connecting but does seem to stop it updating things like the player count in the connection tab.

[mcxboxbroadcast] [Primary Session] Failed to update session information!
com.rtm516.mcxboxbroadcast.core.exceptions.SessionUpdateException
    at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.updateSessionInternal(SessionManagerCore.java:271)
    at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:136)
    at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:128)
    at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.tick(MCXboxBroadcastExtension.java:211)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by rtm516** [comment]
Can you provide a full log file?

**Comment by CodeAX2** [comment]
I am also receiving a similar warning message.

I am running:
MCXboxBroadcast Extension build 49 (git-master-6b1a014)
Geyser-Spigot 2.4.2-b650 (git-master-7da1d7d)
Paper 1.21-99-master@f1f01a1

My log file is available at the hastebin link here: https://hastebin.com/share/cuvowarani.php
I have censored out IP addresses, but those should be irrelevant.
