### ISSUE TITLE
Doesn't work in 1.21.30

### ISSUE THREAD

**Issue by Electronik21** [MCXboxBroadcast/Broadcaster#147]
I just updated my server to the latest geyser build, and when I try to join on bedrock 1.21.30, the client gets stuck on "connecting to multiplayer game" and doens't do anything. It writes this error in console:

```
[12:34:41 INFO]: [STDOUT] [com.phono.srtplight.Log$1] ERROR: 1726590881156 AssocRcv3->Checksums don't match bba714a3 vs 267356cf
[12:34:41 INFO]: [STDOUT] [com.phono.srtplight.Log$1] ERROR: 1726590881157 AssocRcv3->for packet 1388daa400000000bba714a30100001ee5354ae600500000ffffffff3f285e40c00000048008000682c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[12:34:41 WARN]: pe.pi.sctp4j.sctp.messages.exceptions.ChecksumException
[12:34:41 WARN]:        at pe.pi.sctp4j.sctp.messages.Packet.checkChecksum(Packet.java:196)
[12:34:41 WARN]:        at pe.pi.sctp4j.sctp.messages.Packet.<init>(Packet.java:67)
[12:34:41 WARN]:        at pe.pi.sctp4j.sctp.Association$1.run(Association.java:252)
[12:34:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
```

**Comment by rtm516** [comment]
Fixed by https://github.com/MCXboxBroadcast/Broadcaster/commit/7b791e27d8ef7f3add150e4b242f0bbbbfda2ded
Update to build 57+

**Comment by Electronik21** [comment]
Works perfectly now, thank you!
