### ISSUE TITLE
Unable to connect to World

### ISSUE THREAD

**Issue by Xenomatiker** [MCXboxBroadcast/Broadcaster#155]
Hellllloooo,

**Problem:**
When trying to join via the linked profile over xbox live, I receive the above-mentioned error report: 
![grafik](https://github.com/user-attachments/assets/1104b3ef-ecd3-4e86-a319-243552a9512e)

_I already looked through the other threads, but couldn't find anything related._ 

**System information:**
- Ubuntu server: 24.04LTS
- Docker version: 24.0.5
-
- Bedrock Server: 1.21.31.04
- Playit.gg proxy for Docker: ? Latest
- MCXboxBroadcast: Standalone build 49 (git-master-6b1a014)

**How it is supposed to be:**
As you can see, I'm running everything in Docker container:
![Screenshot 2024-10-19 204039](https://github.com/user-attachments/assets/ddfa69b7-8319-4349-97df-d6eff83c75ee)

The way I would like the traffic to work:
**Dedicated Server --> Playit.gg Proxy --> MCXboxBroadcast**

**What works so far:**
- I can connect to the Server via lan
- I can connect manual over the proxy (Domain: self-horrible.gl.at.ply.gg, Port: 22080)
- The Broadcast connects to my account and gets shown under friends tab: 
![grafik](https://github.com/user-attachments/assets/78813899-b778-4de0-bc07-54dd993dc9d2)

_(yes, I have set up the proxy domain and port in config.yml:
![grafik](https://github.com/user-attachments/assets/b3c38534-8970-4cd7-9333-c047af9d3712)_

 _(I also tried the assigned IP instead of the domain with same result. Interestingly it finds the server name even when not specified in the config, but still unable to connect)_
 
 Do you know what I messed up here? Please heeeeälllp mee

**Comment by Xenomatiker** [comment]
latest.log:

[19:16:32.172 main/INFO] Starting MCXboxBroadcast Standalone build 49 (git-master-6b1a014)
[19:16:34.329 main/ERROR] [Primary Session] Failed to ping server
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.updateSessionInfo(Stan>        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.ja>Caused by: java.util.concurrent.TimeoutException
        at com.nukkitx.network.raknet.RakNetClient.onTick(RakNetClient.java:121) ~[MCXboxBroadca>        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[MCXboxBroadcastSt>        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[MCXb>        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174>        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java>        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecu>        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[MCXboxBroadcastS>        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.ja>        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[MCXboxBro>        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[19:16:34.341 main/INFO] [Primary Session] Starting SessionManager...
[19:16:34.409 main/INFO] [Primary Session] Successfully authenticated as Saltstrand (25354276353>[19:16:34.409 main/INFO] [Primary Session] Creating Xbox LIVE session...
[19:16:38.572 main/INFO] [Primary Session] Creation of Xbox LIVE session was successful!
[19:17:09.443 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:17:40.079 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:18:10.733 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:18:41.682 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:19:12.340 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:19:42.986 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:20:13.915 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:20:44.926 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:21:15.575 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:21:46.266 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:22:17.148 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:22:47.814 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:23:18.522 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:23:49.153 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!
[19:24:19.815 MCXboxBroadcast Thread-1/INFO] [Primary Session] Updated session!

**Comment by Xenomatiker** [comment]
Could it maybe be because it can't ping the server as seen in the logs? I tried it as client and it works and the host machine got access out:

![grafik](https://github.com/user-attachments/assets/5b11744d-43ba-467e-92b8-c468c09a5c4b)
Maybe because of IpV6?

**Comment by Xenomatiker** [comment]
hmmmmm.

Tried also IPv4:
- 147.185.221.16 : 22080

Did also not work --> Same issue

**Comment by rtm516** [comment]
> hmmmmm.
> 
> Tried also IPv4:
> 
> * 147.185.221.16 : 22080
> 
> didn't work either --> Same issue

If you cant connect over some form of IP without the tool then the tool wont work

**Comment by rtm516** [comment]
Also just noticed looks like your using the old container image which wont be updated, please use `ghcr.io/mcxboxbroadcast/standalone:latest`

**Comment by Xenomatiker** [comment]
Thanks, that was my issue.

Could u update this in the README, so others won't have the same struggle?

![grafik](https://github.com/user-attachments/assets/db4ccc6e-3ce2-47c2-8f81-8702a70888f2)
