### ISSUE TITLE
Console error when starting Velocity with MCXboxBroadcaster

### ISSUE THREAD

**Issue by JorisvD01** [MCXboxBroadcast/Broadcaster#159]
Hello,

I've installed MCXboxBroadcaster on my Velocity proxy in the Geyser extensions folder, but its giving this error upon startup of the server;

```
[21:31:23 ERROR] [org.geysermc.geyser.event.GeyserEventBus]: An exception occurred while executing event for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "this.mappings" is null
at org.geysermc.geyser.registry.AbstractMappedRegistry.get(AbstractMappedRegistry.java:57) ~[?:?]
at org.geysermc.geyser.GeyserImpl.provider(GeyserImpl.java:792) ~[?:?]
at org.geysermc.geyser.api.command.Command.builder(Command.java:123) ~[?:?]
at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.onCommandDefine(MCXboxBroadcastExtension.java:41) ~[?:?]
at org.lanternpowered.lmbda.Lmbda$23.accept(Unknown Source) ~[server.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[?:?]
at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[?:?]
at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[?:?]
at org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[?:?]
at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) ~[?:?]
at org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) ~[?:?]
at org.geysermc.geyser.command.CommandRegistry.<init>(CommandRegistry.java:163) ~[?:?]
at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.onGeyserInitialize(GeyserVelocityPlugin.java:127) ~[?:?]
at org.geysermc.geyser.platform.velocity.GeyserVelocityPlugin.onInit(GeyserVelocityPlugin.java:197) ~[?:?]
at org.geysermc.geyser.platform.velocity.Lmbda$7.execute(Unknown Source) ~[?:?]
at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[server.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[server.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[server.jar:3.4.0-SNAPSHOT (git-08a42b37-b449)]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

Later on it does say the Extension has started, but also with the following log:

```
.... [21:31:26 INFO] [geyser]: [mcxboxbroadcast] Starting MCXboxBroadcast Extension build 62 (git-master-2a19373)
....2024-10-29T20:31:27.148354800Z Geyser-Velocity - Task Executor #0 ERROR Cannot set JUL log level through log4j-api: ignoring call to Logger.setLevel(OFF)
2024-10-29T20:31:27.245909530Z Geyser-Velocity - Task Executor #0 ERROR Cannot set JUL log level through log4j-api: ignoring call to Logger.setLevel(OFF)
[21:31:27 INFO] [JitsiConfig]: Initialized newConfig: system properties
....2024-10-29T20:31:27.270236254Z Geyser-Velocity - Task Executor #0 ERROR Cannot set JUL log level through log4j-api: ignoring call to Logger.setLevel(OFF)
[21:31:27 INFO] [org.jitsi.config.ReadOnlyConfigurationService]: net.java.sip.communicator.SC_HOME_DIR_LOCATION not set
.... [21:31:27 INFO] [JitsiConfig]: Initialized legacyConfig: sip communicator props (no description provided)
.... [21:31:27 INFO] [JitsiConfig]: Replacing newConfig with
.... [21:31:27 INFO] [geyser]: Done (4.053s)! Run /geyser help for help!
```

Any idea's on how to fix this? Thanks in advance!

**Comment by JorisvD01** [comment]
Some time later it will also give this error:

`.... [21:33:28 ERROR] [geyser]: [mcxboxbroadcast] [Auth] Failed to get/refresh auth token
java.util.concurrent.TimeoutException: Failed to get MSA Code. Login timed out
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaDeviceCodeMsaCode.execute(StepMsaDeviceCodeMsaCode.java:81) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaDeviceCodeMsaCode.execute(StepMsaDeviceCodeMsaCode.java:37) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaToken.getFromInput(StepMsaToken.java:68) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaToken.getFromInput(StepMsaToken.java:36) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.BiMergeStep.getFromInput(BiMergeStep.java:53) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.BiMergeStep.getFromInput(BiMergeStep.java:23) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.AuthManager.initialise(AuthManager.java:115) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.AuthManager.getXboxToken(AuthManager.java:162) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:127) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:144) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:79) ~[?:?]
at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:213) ~[?:?]
at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$4(MCXboxBroadcastExtension.java:185) ~[?:?]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

I've already linked my Bedrock account using the method described in the github page

**Comment by rtm516** [comment]
Looks like your server is unable to reach xbox, and the first issue is potentially outdated geyser
