### ISSUE TITLE
Support for 1.21.44

### ISSUE THREAD

**Issue by NicklasMatzulla** [MCXboxBroadcast/Broadcaster#164]
Hello everyone,
Mojang has recently released Minecraft Bedrock version 1.21.44. If this protocol version is installed, Bedrock players will not be able to join the server via the broadcaster.

Kind regards

**Comment by rtm516** [comment]
Please share the error message the client is getting. There should be no issue on the latest version with 1.21.44

**Comment by Bossbirdyman51** [comment]
Hello :

I think I have the same issue no ?

[22:48:43 INFO] [Primary Session] Creating Xbox LIVE session...
Exception in thread "main" com.rtm516.mcxboxbroadcast.core.exceptions.SessionUpdateException: Unable to update session information, got status 403 trying to update
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.updateSessionInternal(SessionManagerCore.java:308)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.updateSession(SessionManager.java:138)
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.createSession(SessionManagerCore.java:222)
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:162)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:79)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.createSession(StandaloneMain.java:102)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:82)
        
        
        Thanks for help

**Comment by rtm516** [comment]
> Hello :
> 
> I think I have the same issue no ?
> 
> [22:48:43 INFO] [Primary Session] Creating Xbox LIVE session... Exception in thread "main" com.rtm516.mcxboxbroadcast.core.exceptions.SessionUpdateException: Unable to update session information, got status 403 trying to update at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.updateSessionInternal(SessionManagerCore.java:308) at 

Thats an xbox issue
[Looks like an xbox issue](https://support.xbox.com/en-GB/xbox-live-status)

**Comment by Bossbirdyman51** [comment]
> > Hello :
> > I think I have the same issue no ?
> > [22:48:43 INFO] [Primary Session] Creating Xbox LIVE session... Exception in thread "main" com.rtm516.mcxboxbroadcast.core.exceptions.SessionUpdateException: Unable to update session information, got status 403 trying to update at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.updateSessionInternal(SessionManagerCore.java:308) at
> 
> Thats an xbox issue https://support.xbox.com/en-GB/xbox-live-status

Okay thanks, I still have the same problem even though the services are restored.

**Comment by rtm516** [comment]
If you still have issues, I suggest logging into the xbox site with your account and seeing if it asks for any verification. 403 is an error returned by the xbox servers and not something in my code.
