### ISSUE TITLE
MalformedJsonException on Startup

### ISSUE THREAD

**Issue by TylerJohnson177** [MCXboxBroadcast/Broadcaster#165]
MCXboxBroadcast works perfectly fine most of the time, but every once in a while the tool will hard crash on startup with a MalformedJsonException. I have two instances of the tool running (both of them restart 3 times a day), and this has only happened twice in a period of 2 weeks. When this happens, MCXboxBroadcast will completly lock up and become unresponsive. (restart, exit, etc commands do not work) and I have to force close the tool and start it back up again. Also, since the tool hard crashes, the error is not logged to the latest.log file, but it shows most of it in the terminal. (botton 11 lines are missing)

After some testing I found out that this issue persisted with one of my instances, and would happen everytime I would attempt to restart the tool. For some reason, deleting the config.yml file, letting it regenerate, and setting it up to connect to my server fixed the issue. (I first attempted to delete the cache folder and sign into my account again and got a different error when I started up the tool, maybe this contributed to the fix). I have noticed that there has been some additions to the config.yml, but my other session is using the old one without issue.

Build: 63
Version: Standalone
OS: Linux (Debian)
Java Version: 21

**Here is the error I copied from the terminal**

[15:30:03 INFO] Starting MCXboxBroadcast Standalone build 63 (git-master-262c774)
[15:30:04 INFO] [Primary Session] Starting SessionManager...
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setStrictness(Strictness.LENIENT) to accept malformed JSON at line 1 column 9373 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
        at com.google.gson.Gson.assertFullConsumption(Gson.java:1472)
        at com.google.gson.Gson.fromJson(Gson.java:1263)
        at com.google.gson.Gson.fromJson(Gson.java:1171)
        at com.google.gson.Gson.fromJson(Gson.java:1107)
        at net.raphimc.minecraftauth.util.JsonUtil.parseString(JsonUtil.java:29)
        at com.rtm516.mcxboxbroadcast.core.AuthManager.initialise(AuthManager.java:107)
        at com.rtm516.mcxboxbroadcast.core.AuthManager.getXboxToken(AuthManager.java:162)
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:127)
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:144)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:79)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.createSession(StandaloneMain.java:102)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:82)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setStrictness(Strictness.LENIENT) to accept malformed JSON at line 1 column 9373 path $
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1754)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1550)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:625)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:507)
        at com.google.gson.Gson.assertFullConsumption(Gson.java:1468)
        ... 11 more

**Comment by rtm516** [comment]
This is caused by a corrupt auth cache file. Please delete it and relogin, if it keeps happening it could be a problem with your disk.
