### ISSUE TITLE
Not working on latest version of Paper

### ISSUE THREAD

**Issue by Golden-D60** [MCXboxBroadcast/Broadcaster#166]
I am using the latest snapshot version of Paper on my server which is 1.21.3. I am also using the latest version of Geyser (2.5.0-SNAPSHOT) and floodgate (2.2.3-SNAPSHOT (b114-83fbd6e)). Connecting to the server works perfectly fine by IP, but using the latest version of MCXboxBroadcast (version 67) throws this error within the console upon connecting on Minecraft bedrock:

```
[20:48:17 INFO]: [STDOUT] [com.phono.srtplight.Log$1] ERROR: 1731962897376 AssocRcv1->Checksums don't match 7654d614 vs d7ac9de8
[20:48:17 INFO]: [STDOUT] [com.phono.srtplight.Log$1] ERROR: 1731962897381 AssocRcv1->for packet 1388f538000000007654d6140100001e0e644bac00500000ffffffffad9edaa3c00000048008000682c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
[20:48:17 WARN]: pe.pi.sctp4j.sctp.messages.exceptions.ChecksumException
[20:48:17 WARN]:        at pe.pi.sctp4j.sctp.messages.Packet.checkChecksum(Packet.java:196)
[20:48:17 WARN]:        at pe.pi.sctp4j.sctp.messages.Packet.<init>(Packet.java:67)
[20:48:17 WARN]:        at pe.pi.sctp4j.sctp.Association$1.run(Association.java:252)
[20:48:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
```

On the client side, Minecraft gets stuck on "Connecting to multiplayer game..." for a very long time before saying "Check your internet connection" and "Unable to connect to world".

**Comment by Golden-D60** [comment]
Turns out I wasn't using the latest version even though I thought I did. It still doesn't work, now getting past locating server, going back to connecting to multiplayer game again and then saying "Unable to connect to world" with no information in the server console. Forgot to mention that this server is running locally in a Windows server I'm running at home.

**Comment by rtm516** [comment]
You need to port forward and have an internet accessible IP for others to join, then make sure the mcxb config is changed from `remote-address: auto` to your accessible IP

**Comment by Golden-D60** [comment]
Ah right, thank you! I will try this tommorow.
