### ISSUE TITLE
Error on boot with build 66

### ISSUE THREAD

**Issue by Dalethium** [MCXboxBroadcast/Broadcaster#170]
```
Failed to get/refresh auth token
java.lang.NullPointerException: Cannot invoke "com.rtm516.mcxboxbroadcast.core.configs.NotificationConfig.sessionExpiredMessage()" because "this.config" is null
        at com.rtm516.mcxboxbroadcast.core.notifications.BaseNotificationManager.sendSessionExpiredNotification(BaseNotificationManager.java:22) ~[MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.AuthManager.lambda$initialise$0(AuthManager.java:117) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.msa.StepMsaDeviceCode.execute(StepMsaDeviceCode.java:70) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.msa.StepMsaDeviceCode.execute(StepMsaDeviceCode.java:37) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.msa.StepMsaToken.getFromInput(StepMsaToken.java:68) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.msa.StepMsaToken.getFromInput(StepMsaToken.java:36) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.BiMergeStep.getFromInput(BiMergeStep.java:53) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.BiMergeStep.getFromInput(BiMergeStep.java:23) ~[MCXboxBroadcastStandalone.jar:?]
        at net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.AuthManager.initialise(AuthManager.java:115) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.AuthManager.getXboxToken(AuthManager.java:162) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:127) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:144) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:79) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.createSession(StandaloneMain.java:102) [MCXboxBroadcastStandalone.jar:?]
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:82) [MCXboxBroadcastStandalone.jar:?]
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.rtm516.mcxboxbroadcast.core.models.auth.XboxTokenInfo.gamertag()" because "tokenInfo" is null
        at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:145)
        at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:79)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.createSession(StandaloneMain.java:102)
        at com.rtm516.mcxboxbroadcast.bootstrap.standalone.StandaloneMain.main(StandaloneMain.java:82)
```
        
This seems to happen each time the server starts. Please let me know if I can provide more context.

**Comment by rtm516** [comment]
Delete the config and restart, there will likely be an error further up saying the config is corrupt
