### ISSUE TITLE
[geyser]: [mcxboxbroadcast] [Auth] Failed to get/refresh auth token

### ISSUE THREAD

**Issue by JorisvD01** [MCXboxBroadcast/Broadcaster#175]
Hey,
I've just installed the geyser extension on my server but after logging in with my account I get this error in the console;
`>.... [14:30:16 ERROR] [geyser]: [mcxboxbroadcast] [Auth] Failed to get/refresh auth token
com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.responsehandler.exception.MsaRequestException: status: 400 Bad Request, error: invalid_grant, error message: The user could not be authenticated or user interaction is required. The user must sign in again and if needed grant the client application access to the requested scope.
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.responsehandler.MsaResponseHandler.handleJsonError(MsaResponseHandler.java:31) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.responsehandler.JsonHttpResponseHandler.handle(JsonHttpResponseHandler.java:45) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.responsehandler.JsonHttpResponseHandler.handle(JsonHttpResponseHandler.java:30) ~[?:?]
at net.lenni0451.commons.httpclient.HttpClient.execute(HttpClient.java:213) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaDeviceCodeMsaCode.execute(StepMsaDeviceCodeMsaCode.java:61) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaDeviceCodeMsaCode.execute(StepMsaDeviceCodeMsaCode.java:37) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaToken.getFromInput(StepMsaToken.java:68) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.msa.StepMsaToken.getFromInput(StepMsaToken.java:36) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.BiMergeStep.getFromInput(BiMergeStep.java:53) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.BiMergeStep.getFromInput(BiMergeStep.java:23) ~[?:?]
at com.rtm516.mcxboxbroadcast.shaded.net.raphimc.minecraftauth.step.AbstractStep.getFromInput(AbstractStep.java:77) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.AuthManager.initialise(AuthManager.java:115) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.AuthManager.getXboxToken(AuthManager.java:162) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.getXboxToken(SessionManagerCore.java:127) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.SessionManagerCore.init(SessionManagerCore.java:144) ~[?:?]
at com.rtm516.mcxboxbroadcast.core.SessionManager.init(SessionManager.java:79) ~[?:?]
at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.createSession(MCXboxBroadcastExtension.java:213) ~[?:?]
at com.rtm516.mcxboxbroadcast.bootstrap.geyser.MCXboxBroadcastExtension.lambda$onPostInitialize$4(MCXboxBroadcastExtension.java:185) ~[?:?]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]`

**Comment by rtm516** [comment]
This is normally caused by using a password less login method. When authorising with Microsoft please make sure you Auth with a username and password and don't use one of the password less methods.

**Comment by JorisvD01** [comment]
> This is normally caused by using a password less login method. When authorising with Microsoft please make sure you Auth with a username and password and don't use one of the password less methods.

When I go to the microsoft link they only way I can login is by using a code sent to my email, or using another device. Do you know a way to force use email & password in this case?

**Comment by JorisvD01** [comment]
Ah I just found the solution. I had to enable login by password in my microsoft account.
Thanks for the help!
